package Classe;
// Generated 04/05/2019 19:26:27 by Hibernate Tools 4.3.1



/**
 * Itempedido generated by hbm2java
 */
public class Itempedido  implements java.io.Serializable {


     private Integer id;
     private Pedido pedido;
     private Roupa roupa;
     private int quantidade;
     private double valorUnitario;
     
    public Itempedido() {
    }

    public Itempedido(Integer id, Pedido pedido, Roupa roupa, int quantidade, double valorUnitario) {
        this.id = id;
        this.pedido = pedido;
        this.roupa = roupa;
        this.quantidade = quantidade;
        this.valorUnitario = valorUnitario;
    }

    public int getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }

    public double getValorUnitario() {
        return valorUnitario;
    }

    public void setValorUnitario(double valorUnitario) {
        this.valorUnitario = valorUnitario;
    }

    public Itempedido(Pedido pedido, Roupa roupa) {
       this.pedido = pedido;
       this.roupa = roupa;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public Roupa getRoupa() {
        return this.roupa;
    }
    
    public void setRoupa(Roupa roupa) {
        this.roupa = roupa;
    }




}


