package Classe;
// Generated 04/05/2019 19:26:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private int status;
     private Date dataPedido;
     private double valorTotal;
     private int prazo;

    public Pedido(Integer id, Cliente cliente, int status, Date dataPedido, double valorTotal, int prazo) {
        this.id = id;
        this.cliente = cliente;
        this.status = status;
        this.dataPedido = dataPedido;
        this.valorTotal = valorTotal;
        this.prazo = prazo;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Date getDataPedido() {
        return dataPedido;
    }

    public void setDataPedido(Date dataPedido) {
        this.dataPedido = dataPedido;
    }

    public double getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(double valorTotal) {
        this.valorTotal = valorTotal;
    }

    public int getPrazo() {
        return prazo;
    }

    public void setPrazo(int prazo) {
        this.prazo = prazo;
    }
     private Set itempedidos = new HashSet(0);

    public Pedido() {
    }

    public Pedido(Cliente cliente, int status, Set itempedidos) {
       this.cliente = cliente;
       this.status = status;
       this.itempedidos = itempedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    public Set getItempedidos() {
        return this.itempedidos;
    }
    
    public void setItempedidos(Set itempedidos) {
        this.itempedidos = itempedidos;
    }
}


