package Classe;
// Generated 04/05/2019 19:26:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private String status;
     private Set itempedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, String status) {
        this.cliente = cliente;
        this.status = status;
    }
    public Pedido(Cliente cliente, String status, Set itempedidos) {
       this.cliente = cliente;
       this.status = status;
       this.itempedidos = itempedidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getItempedidos() {
        return this.itempedidos;
    }
    
    public void setItempedidos(Set itempedidos) {
        this.itempedidos = itempedidos;
    }




}


